apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goit-argo
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 7.7.0
      helm:
        valueFiles:
          - $values/argocd-values.yaml
    - repoURL: https://github.com/tatiana-lapteva/lesson-7.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true